Sb subject view
ucd-library/rp-ucd-client pull request #317
Opened 2022-02-10 05:11 UTC by sbagg

This is referring to issue Identify subject for "view all X" items accessed via subject pages #294.  Completed and in need of review.

2022-02-16 00:09 UTC, qjhart requested changes

2022-02-16 00:09 UTC, qjhart commented on client/public/elements/pages/concept/rp-page-concept.js
> +    console.log(this.tempResearch );
comment out

2022-02-16 00:09 UTC, qjhart commented on client/public/src/models/CollectionModel.js
> +    console.log("MainFacet", payload);
Comment out

2022-02-16 00:09 UTC, qjhart commented on client/public/src/models/CollectionModel.js
> +      console.log("subFacets:", subFacets);
Comment Out

2022-02-16 00:09 UTC, qjhart commented on client/public/src/models/CollectionModel.js
> +      console.log("subFacets:", subFacets);
Comment Out

2022-02-16 00:09 UTC, qjhart commented on client/public/elements/pages/concept/rp-page-concept.tpl.js
> +            ${v <= 10 ? html`
Should this be v<= 8 ?

2022-02-16 00:52 UTC, qjhart approved these changes

2022-02-16 00:55 UTC, merged

2022-03-10 23:15 UTC, jrmerz commented
@sbagg @qjhart This PR added some suspect code: https://github.com/ucd-library/rp-ucd-client/blame/jm-ucdid-switch/client/public/elements/utils/rp-utils-collection.js#L274 ... can you please investigate, it's throwing a bug for me.  To start, data.id only has 1 __ in it.  Please add a little inline documentation as well.